# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: MM
email:
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
twitter_username: username
github_username: username
minimal_mistakes_skin: default
search: true

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: Asia/Seoul
highlighter: rouge
include:
  - _pages

#
# Markdown settings
#
kramdown:
  input:                     GFM
  auto_ids:                  true
  footnote_nr:               1
  entity_output:             as_char
  toc_levels:                1..6
  smart_quotes:              lsquo,rsquo,ldquo,rdquo
  enable_coderay:            false
  hard_wrap:                 false
  syntax_highlighter:        rouge
  syntax_highlighter_opts:
    css_class:               "highlight"
  transliterated_header_ids: true
  footnote_backlink:         "&#8617;&#xfe0e;"


# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name   : "Jaehyun Park"
  avatar : "/assets/images/bio-photo.jpg"
  bio    : "안녕하세요, 아직 세상에 많이 남아있는 다양한 문제들을 제 기술력으로 해결 하고싶은 개발자 박재현입니다."
  links:
    - label: "Website"
      icon: "fas fa-fw fa-link"
      url: "https://jaehyunup.github.io"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/jaehyunup"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://instagram.com/jaehyun.co.kr"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://instagram.com/jaehyun.co.kr"  

footer:
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/jaehyunup"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://instagram.com/jaehyun.co.kr"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://instagram.com/jaehyun.co.kr"  

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
